config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :recipes do
    resources :likes, only: %i[create destroy]
  end

  resources :categories 
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipes, through: :preparation
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user

  validates :user, uniqueness: {scope: :recipe, message: 'already liked'}
end

app/models/preparation.rb
class Preparation < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title, :description, :difficulty_level, presence: true
  validates :difficulty_level, presence: true, inclusion: { in: 1..5, message: 'Difficulty level has to be between 1-5' }
  has_many :likes
  has_many :users, through: :likes

  mount_uploaders :images, ImageUploader

  belongs_to :category
  has_many :ingredients, through: :preparation
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.save
    render json: @category.as_json
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]

  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.save
    render json: @ingredient.as_json
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy
  end

  private

  def ingrediend_params
    params.require(:ingredient).permit(:name)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = Like.new(recipe_id: params[:recipe_id], user: current_user)
    like.save

    redirect_to recipe_path(like.recipe)
  end

  def destroy
    like = Like.find(params[:id])
    like.destroy

    redirect_to recipe_path(like.recipe)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: %i[create update edit destroy]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
    @categories = Category.all
  end

  def create
    @recipe = Recipe.create(recipe_params)

    if @recipe.save
      redirect_to @recipe
    else
      render 'new'
    end
  end
 
  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :difficulty_level, :description, :image, :category_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category, html: { class: 'form-inline' }) do |f| %>
  <p>
    <%= f.input :name %>
  </p>
  <p>
    <%= f. button :submit, 'Add a categoy', class: "btn btn-primary"  %>
  </p>
<% end %>

app/views/categories/index.html.erb
<h1>Categories</h2>

<table>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>

  <% @categories.each do |category| %>
   <tr>
      <td><%= category.name %></td>
    </tr>
  <% end %>
</table>

<h2><%= link_to 'Add a category', new_category_path %></h2>

<p><%= link_to 'Back to main page', recipes_path %></p>

app/views/categories/new.html.erb
<h1> New Category </h1>

<%= render 'form' %>

<%= link_to 'Back index', recipes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if notice %>
      <div class ="alert alert-info">
        <%= notice %>
      </div>
    <% end %>

    <% if alert %>
      <div class ="alert alert-danger">
        <%= alert %>
      </div>
    <% end %>

    <% if current_user %>
      <p>Hello <%= current_user.email %> !!!
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      </p>
    <% else %>
      <%= link_to "Sign in", new_user_session_path %>
      <%= link_to "Sign up", new_user_registration_path %>
    <% end %>

    <div class ='container'>
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/recipes/_form.html.erb
<%= simple_form_for(@recipe, html: { class: 'form-inline' }, ) do |f| %>

  <% if @recipe.errors.any? %>
    <div id='error_messages'>
      <h2> Because of
        <%= pluralize(@recipe.errors.count, 'error') %>
        this recipe could not be saved.
      </h2>
      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.input :title, placeholder: 'Enter recipe title' %>
  </p>

  <p>
    <%= f.input :difficulty_level, collection: 1..5, prompt: "Select difficulty" %>
  </p>

  <p>
    <%= f.input_field :description, placeholder: 'Description' %>
  </p>

  <p>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.association :category %>
   </p>

  <p>
    <%= f. button :submit, class: "btn btn-primary" %>
  </p>
<% end %>

app/views/recipes/edit.html.erb
<h1> Edit Recipe </h1>

<%= render 'form' %>

<%= link_to 'Back to index', recipes_path %>

app/views/recipes/index.html.erb
<h1>All Recipes</h2>

<p><%= link_to 'Add a recipe', new_recipe_path %></p>
<table>
  <tr>
    <th>Title</th>
    <th>Difficulty level</th>
    <th>Description</th>
    <th></th>
  </tr>

  <% @recipes.each do |recipe| %>
   <tr>
      <td><%= link_to "#{recipe.title}", recipe_path(recipe) %></td>
      <td><%= recipe.difficulty_level %></td>
      <td><%= recipe.title %></td>
      <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
      <td><%= link_to 'Delete', recipe_path(recipe),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<h2><%= link_to 'Add a category', new_category_path %></h2>

<p><%= link_to 'Back to main page', welcome_index_path %></p>

app/views/recipes/new.html.erb
<h1> New Recipe </h1>

<%= render 'form' %>

<%= link_to 'Back to index', recipes_path %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>

<p>Difficulty level: <%= @recipe.difficulty_level%></p>
<p>Category: <%= @recipe.category.name%></p>
<p>Description: <%= @recipe.description%></p>
<p><%= link_to 'Back to index', recipes_path %></p>

app/views/welcome/index.html.erb
<h1>Welcome to Cook Book</h1>
<p>by Marta K</p>
<p><%= link_to 'View recipes', recipes_path %></p>